name: Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
    # Gradlew 실행 허용
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    # JDK 11 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    # 환경 변수 설정
    - name: Set environment values
      run: |
        cd ./src/main/resources
        touch ./env.properties
        echo "${{ secrets.ENV }}" > ./env.properties
      shell: bash
    # Gradle build (Test 제외)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build -x test
    # Docker build
    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t beachcombing .
        docker tag beachcombing future430/beachcombing:${GITHUB_SHA::7}
        docker push future430/beachcombing:${GITHUB_SHA::7}
    # Deploy (docker_compose 사용)
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_ELASTIC_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PEM_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker pull future430/beachcombing:${GITHUB_SHA::7}
          sudo docker tag future430/beachcombing:${GITHUB_SHA::7} beachcombing
          sudo docker-compose up -d 
